<?php

declare(strict_types=1);

/**
 * Example of the generated Paymos configuration file.
 *
 * The real `paymos/paymos-config.php` is generated by the Paymos dashboard and
 * injected into the module ZIP you download — you do NOT create or edit it by
 * hand, and you never type secrets in the PrestaShop admin. This file documents
 * the v2 shape so you can recognise it; copy it to `paymos-config.php` only for
 * local development.
 *
 * Values from this file are read-only and OVERRIDE anything stored in the
 * PrestaShop admin. `base_url` defaults to https://api.paymos.io when omitted.
 */

return array(
    'config_version' => 2,
    'environments' => array(
        'sandbox' => array(
            'base_url' => 'https://api.paymos.io',
            'api_key' => 'pk_test_replace_me',
            'api_secret' => 'sk_test_replace_me',
            'project_id' => 'prj_replace_me',
            'webhook_secret' => 'whsec_replace_me',
        ),
        'live' => array(
            'base_url' => 'https://api.paymos.io',
            'api_key' => 'pk_live_replace_me',
            'api_secret' => 'sk_live_replace_me',
            'project_id' => 'prj_replace_me',
            'webhook_secret' => 'whsec_replace_me',
        ),
    ),
);
